sudo: false
cache: bundler
language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
env:
  - RAILS_VERSION=5.0
  - RAILS_VERSION=5.1
  - RAILS_VERSION=5.2
before_install: gem install bundler -v 1.16.0.pre.2
